name: Replicaci贸n de Bases de Datos

on:
  schedule:
    # Ejecuta cada 5 minutos (cron syntax)
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Permite ejecuci贸n manual

jobs:
  replicacion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout c贸digo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install oracledb mysql-connector-python psycopg2-binary

    - name: Configurar Oracle Instant Client
      run: |
        # Descargar y configurar Instant Client
        wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
        unzip instantclient-basiclite-linuxx64.zip
        echo "$(pwd)/instantclient_*" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$(pwd)/instantclient_*" >> $GITHUB_ENV

    - name: Configurar Wallet
      env:
        WALLET_CONTENT: ${{ secrets.ORACLE_WALLET }}
      run: |
        mkdir -p wallet
        echo "$WALLET_CONTENT" | base64 --decode > wallet.zip
        unzip wallet.zip -d wallet
        echo "TNS_ADMIN=$(pwd)/wallet" >> $GITHUB_ENV

    - name: Ejecutar script de replicaci贸n
      env:
        ORACLE_USER: ${{ secrets.ORACLE_USER }}
        ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        # ... agregar todas las variables necesarias
      run: python script.py
